# Generated by Django 4.0.6 on 2022-09-21 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vids', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reels',
            name='reel',
            field=models.FileField(upload_to='shorts/% y/ %m/% d/'),
        ),
    ]
