# Generated by Django 4.0.6 on 2022-09-21 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vids', '0002_alter_reels_reel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reels',
            name='reel',
            field=models.FileField(upload_to='shorts/'),
        ),
    ]
