# Generated by Django 4.0.6 on 2022-09-21 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vids', '0004_reels_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
