# Generated by Django 4.0.6 on 2022-09-23 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vids', '0005_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
