# Generated by Django 4.0.6 on 2022-09-24 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vids', '0006_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reels',
            name='desc',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
